export const NODE_TYPES = [
  "INITIAL",
  "MANUAL_TRIGGER",
  "HTTP_REQUEST",
  "GOOGLE_FORM_TRIGGER",
  "STRIPE_TRIGGER",
  "GEMINI",
  "GROQ",
  "DISCORD",
  "SLACK",
] as const;

export const NodeType = {
  INITIAL: "INITIAL",
  MANUAL_TRIGGER: "MANUAL_TRIGGER",
  HTTP_REQUEST: "HTTP_REQUEST",
  GOOGLE_FORM_TRIGGER: "GOOGLE_FORM_TRIGGER",
  STRIPE_TRIGGER: "STRIPE_TRIGGER",
  GEMINI: "GEMINI",
  GROQ: "GROQ",
  DISCORD: "DISCORD",
  SLACK: "SLACK",
} as const;

export type NodeType = (typeof NODE_TYPES)[number];
